### PR TITLE
[0.3.x] explicitly state no ordering on data from Provider APIs

### PR DESCRIPTION
**Pull request by yoimnik**
### `Provider` or `agency`

Which API(s) will this pull request impact:

* [x] `provider`
* [ ] `agency`
* [ ] both

### Additional context

Discussed on the MDS Provider web conference 5/9 11am PT

### CODE REVIEW

**Comment by karcass** [comment]
Looks good to me

**Comment by hunterowens** [comment]
@yoimnik we got something similar to this into `dev` and therefore `0.3.2` right?

**Comment by thekaveman** [comment]
Yeah I think this conflicts with what got merged in #301.

**Comment by hunterowens** [comment]
closing, then! thanks for pushing this up @yoimnik and glad we now have ordering added.

**Comment by thekaveman** [comment]
I may have been mistaken as to the purpose of #301, see [@rf- comments on #277](https://github.com/CityOfLosAngeles/mobility-data-specification/pull/277#issuecomment-506814102)

**Pull request closed without merging**
