### PR TITLE
Register Cargoroo as a mobility provider

### PR DESCRIPTION
**Pull request by danielbynight**
---
name: Daniel Matias Ferrer (@danielbynight) from Cargoroo
about: providers.csv
title: Register Cargoroo as a mobility provider 

---

# MDS Pull Request

## Explain pull request

I've opened this pull request to register Cargoroo in the list of mobility providers.

### CODE REVIEW

**Comment by danielbynight** [comment]
I see "Contributor License Agreement is not signed yet" in this pull request, yet I have signed it (once clicking on "Details", I'm told "You have agreed to the CLA for openmobilityfoundation/mobility-data-specification"). Please let me know if there is anything I should do to validate the signing of this CLA.

**Comment by danielbynight** [comment]
> Hello Daniel, We do not understand what service you are seeking and no details or comments are included in your email to us. If you need further assistance, or would rather speak to a live representative regarding this issue please contact 3-1-1 (213-473-3231). CH

Hi, CH,

I left a commend in the merge request https://github.com/openmobilityfoundation/mobility-data-specification/pull/911, I did not send an email message. I was under the impression that this being a comment in a merge request would provide enough context on what I'm attempting to do. I didn't expect it to be required to contact via email - and if that is preferable, can you please let me know which address I should use? I attempted to call that phone number, but it doesn't seem to be valid - could it be that this is not a Dutch phone number, and if so, could please let me know which country calling code I should use?

I'm attempting to register the service Cargoroo as an MDS provider. I followed [these instructions](https://github.com/openmobilityfoundation/mobility-data-specification/wiki/Adding-an-MDS-Provider-ID) and described the pull request based on the template provided in the description field.

Currently, the pull request indicates that the "Contributor License Agreement is not signed yet.". As I mentioned in the previous comment, I did sign it (to the best of my knowledge). Can you please let me know how to proceed?

**Comment by mplsmitch** [comment]
Hello @danielbynight - There still seems to be a problem with the CLA for this PR.  Is it possible that your commits are linked to the wrong user email address?  The address linked to the commits must match the one accepting the CLA. If that's the case, here's a link on how to fix it: 
https://docs.github.com/en/pull-requests/committing-changes-to-your-project/troubleshooting-commits/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

Ignore that above message from **ITA-WAMS-Service-Account**. Whatever that is it's not associated with OMF/MDS

**Comment by danielbynight** [comment]
Cheers, @mplsmitch - that explains it, I feel a bit silly to have engaged on conversation with a bot 😅

Also that explains the situation with the commits - I've experienced such issues before, since I work with different code repository services and accounts. I will fix it - perhaps by creating a new pull request if needed. Thank you!

**Pull request closed without merging**
