### PR TITLE
[WIP] Provider cleanup

### PR DESCRIPTION
**Pull request by thekaveman**

### CODE REVIEW

**Comment by thekaveman** [comment]
Added the `[WIP]` designation to indicate that I'm still making sure this PR is good to go... stand by.

**Comment by thekaveman** [comment]
@hunterowens @black-tea: `trips` have both the `provider_id` and `provider_name`, as well as a `vehicle_id` and `vin` -- one identifier each for machines and humans. 

Should `status_changes` mirror this approach? Currently it has only the "for humans" identifiers.

**Comment by hunterowens** [comment]
Yes, let's duplicate.

**Comment by thekaveman** [comment]
@hunterowens done. I left the field name as `device_id`, based on the discussion in #37, and the conclusion that this is really the identifier for the GPS device, no matter what "vehicle frame" it is attached to. I added a note under *General Information* to reflect this conclusion. 

So this PR should fix #37.

**Pull request merged**
