### PR TITLE
update sherpa gbfs api url

### PR DESCRIPTION
**Pull request by yoimnik**
correcting sherpa gbfs api url in preparation for launch

### CODE REVIEW

**Comment by hunterowens** [comment]
@yoimnik I'm getting 404 on that URL... I assume this is because sherpa hasn't launched yet to my knowledge?

**Comment by yoimnik** [comment]
@hunterowens Yes, Sherpa has not launched yet.

**Comment by karcass** [comment]
Looks good to me

**Comment by hunterowens** [comment]
@yoimnik sorry for not merging this earlier. FYI, link is still 404ing

**Comment by yoimnik** [comment]
@hunterowens hey, this does not seem to be 404ing:

https://mds.bird.co/gbfs/platform-partner/sherpa/gbfs.json

the spec says to use that file as a way to explore all other URLs https://github.com/NABSA/gbfs/blob/master/gbfs.md

when looking at this CSV, is it assumed that what is written as the gbfs_url is a base url, and that clients have to append it with `/<file_name>.json` ? i have assumed that, which is why i wrote the url this way

i believe this assumption applies to the `mds_url`, so i assumed the same thing for the gbfs_url

**Pull request merged**
