### PR TITLE
Add OAauth client_credentials auth guidelines section

### PR DESCRIPTION
**Pull request by dyakovlev**
In previous discussions (linked below) about authenticating MDS requests, there was a preference for not prescribing a specific authentication method. While there are benefits to the MDS protocol definition remaining process-agnostic and not prescriptive, the immediate drawbacks are that cities and data partners struggle to maintain multiple authentication schemes and mobility providers do not have alignment on security best practices for authorization to access MDS data.

In this PR, I propose specifying the OAuth2.0 `client_credentials` grant type as a way to alleviate this. In this auth scheme, a client secret is given by a mobility provider to a city, who can then use it to generate access tokens via the provider’s OAuth2.0 service in a repeatable, documented way. These tokens are commonly supplied in JWT format by many OAuth frameworks, so there is tooling around permissions, identity, and expiry built into the format already, easing the load on providers.

Another useful feature of OAuth grants is token scopes, which can be used for access control for third party applications. E.g. if LA is working with a third party data ingestion platform, using this grant type they can request a token in a (for example) `PARTNER` scope with certain permissions, date boundaries, and expiry/refresh configuration. This token can then be used by the partner without the mobility provider extending to them access to their entire historical MDS API. This may be useful for scoped introduction of new MDS endpoints, as well.

If reasonable/desirable, I can flesh out some suggested scopes and token parameters.

Related discussions:
- https://github.com/CityOfLosAngeles/mobility-data-specification/pull/81 
- https://github.com/CityOfLosAngeles/mobility-data-specification/issues/121

### CODE REVIEW

**Comment by thekaveman** [comment]
Tagging @asadowns and @noonhub as we've traded some thoughts on this recently.

**Comment by noonhub** [comment]
This looks good to me!

**Comment by hunterowens** [comment]
@thekaveman this is a _MAY_ requirement, which makes me think it could be included for an 0.2.1, vs 0.3.0 may bump the requirement to SHALL?

**Comment by noonhub** [comment]
@hunterowens that seems reasonable to me

**Comment by thekaveman** [comment]
Yeah I think this is just providing guidance/suggestions for how to implement auth. There's nothing here that requires OAuth `client_credentials`, so not breaking IMHO.

**Pull request merged**
