### PR TITLE
adding pony as provider

### PR DESCRIPTION
**Pull request by vilesa1**
---
name: Adding Pony as Provider
about: Suggest changes to MDS
title: Adding Pony as Provider

---

# MDS Pull Request

Thank you for your contribution!  Please review our OMF [contributing page](https://github.com/openmobilityfoundation/governance/blob/main/CONTRIBUTING.md) to understand guidelines and policies for participation, and our [Code of Conduct page](https://github.com/openmobilityfoundation/governance/blob/main/CODE_OF_CONDUCT.md).

To avoid complications and help make the Review process as smooth as possible, make sure to:

1. Target [**`dev`**](https://github.com/openmobilityfoundation/mobility-data-specification/tree/dev) branch. Please ensure you are targeting **`dev`**, not **`main`**. 
1. Keep the *"Allow edits from maintainers"* button checked to help us resolve some issues for you.
1. Be ready to resolve any merge conflicts before we approve your Pull Request.
1. Have an up to date profile, per our Github [community profile](https://github.com/openmobilityfoundation/governance/blob/main/CONTRIBUTING.md#community-profile) guildance.

## Explain pull request

Please provide a clear and concise reason for this pull request and the impact of the change

## Is this a breaking change

A breaking change would require consumers or implementors of the API to modify their code for it to continue to function (ex: renaming of a required field or the change in data type of an existing field). A non-breaking change would allow existing code to continue to function (ex: addition of an optional field or the creation of a new optional endpoint).

* Yes, breaking
* No, not breaking
* I'm not sure

## Impacted Spec

Which spec(s) will this pull request impact?

* `agency`
* `policy`
* `provider`

### CODE REVIEW

**Comment by schnuerle** [comment]
This looks good @vilesa1. A few things:

1. Make sure to grab the latest code from the 'dev' branch since there is a conflict right now.
1. Make sure you sign the [CLA here](https://cla-assistant.io/openmobilityfoundation/mobility-data-specification?pullRequest=598) so we can accept your contribution.

We should be able to get this into the next 1.1.0 release.

**Comment by vilesa1** [comment]
thanks

I have fixed the conflict

However I have signed the CLA but it's not being reflected here for some reason

**Comment by schnuerle** [comment]
It looks like @victorlesaux needs to sign it too since that's the account that made the latest fix.

**Comment by vilesa1** [comment]
sorry about that 
I had to move a new PR: https://github.com/openmobilityfoundation/mobility-data-specification/pull/600
closing this one

**Pull request closed without merging**
