### PR TITLE
Add "car" vehicle type

### PR DESCRIPTION
**Pull request by dbaty**
I am working with BlueLA, a car sharing service in Los Angeles. We have implemented the MDS API. 

The MDS API currently has 2 types of vehicle: `bicycle` and `scooter`. I have seen discussions about adding new types (at least #95 #167 #170) but they seem to be stale and/or related to broader subjects (and thus less actionable).

I think that "just" adding a new `car` vehicle type could be an easy and good enough first step.

### CODE REVIEW

**Comment by hunterowens** [comment]
@dbaty can you take a look at #255, as a way to potentially supporting carshare services to MDS?

**Comment by hunterowens** [comment]
@dbaty are you still interested in seeing this merged for 0.4.0 ?

**Comment by tonial** [comment]
Hi @hunterowens, we are still interested in seeing this pull request merged.
I've rebased and updated the change for the Agency API.
I also took the liberty to change the README, if it seems okay to you.

**Comment by margodawes** [comment]
@hunterowens, Seattle is also interested in adding car as one of the vehicle_type fields for 0.4.0 as the car share use case in our city is otherwise compatible with MDS.

**Comment by karcass** [comment]
+1 for car

Also interested in "moped".  Maybe that's a separate PR?

**Comment by hunterowens** [comment]
changed README to read carshare but LGTM

**Pull request merged**
