### PR TITLE
[Agency] API is REST-like, not RESTful

### PR DESCRIPTION
**Pull request by HenriJ**
I don't want to go into any bike-shedding, and it does not matter if an API is RESTful or REST-like. That said, it is nice to use the correct term to define the API, and this one is clearly REST-like (otherwise we would have a "/vehicles" resource that we could PUT and DELETE, not "register_vehicle" and "deregister_vehicle")

### CODE REVIEW

**Comment by hunterowens** [comment]
@toddapetersen do we want to rework agnecy to be true restful or rest-like as is?

**Comment by toddapetersen** [comment]
Yes.

**Comment by HenriJ** [comment]
@toddapetersen "yes" meaning "rework to be true restful" ?
I have a little bit of spare time time in the next days, I could work on it with my team if you are open to it.

**Comment by HenriJ** [comment]
Hi @toddapetersen , any news on that one ?
It would also help us if you could have a look on https://github.com/CityOfLosAngeles/mobility-data-specification/issues/148

**Comment by lionel-panhaleux** [comment]
Hi @toddapetersen, @hunterowens. I submitted a PR for a more RESTful API and can provide adjustments on it if needed.

**Comment by hunterowens** [comment]
@HenriJ Let's close this, in light of merging #194 which is inspired by this work.

**Pull request closed without merging**
